# Install scripts README (and rename)
data/scripts/README usr/share/doc/konversation/README.scripts
# Debian menu XPM icons
debian/*.xpm usr/share/pixmaps

usr/bin/konversation
usr/share/applications/kde4/konversation.desktop
usr/share/doc/kde4/HTML/en/konversation/*
usr/share/icons/hicolor/*
usr/share/kde4/apps/kconf_update/konversation*
usr/share/kde4/apps/konversation/*
usr/share/kde4/services/konvirc.protocol
usr/share/kde4/services/konvirc6.protocol
usr/share/locale/*
