# Install scripts README (and rename)
data/scripts/README usr/share/doc/konversation/README.scripts
# Debian menu XPM icons
debian/*.xpm usr/share/pixmaps

usr/bin/konversation
usr/share/applications/kde4/konversation.desktop
usr/share/doc/kde4/HTML/en/konversation/*
usr/share/icons/hicolor/128x128/apps/konversation.png
usr/share/icons/hicolor/16x16/actions/kimproxyaway.png
usr/share/icons/hicolor/16x16/actions/kimproxyoffline.png
usr/share/icons/hicolor/16x16/actions/kimproxyonline.png
usr/share/icons/hicolor/16x16/apps/konversation.png
usr/share/icons/hicolor/22x22/actions/char.png
usr/share/icons/hicolor/22x22/actions/kimproxyaway.png
usr/share/icons/hicolor/22x22/actions/kimproxyoffline.png
usr/share/icons/hicolor/22x22/actions/kimproxyonline.png
usr/share/icons/hicolor/22x22/actions/konv_message.png
usr/share/icons/hicolor/22x22/apps/konversation.png
usr/share/icons/hicolor/32x32/actions/kimproxyaway.png
usr/share/icons/hicolor/32x32/actions/kimproxyoffline.png
usr/share/icons/hicolor/32x32/actions/kimproxyonline.png
usr/share/icons/hicolor/32x32/apps/konversation.png
usr/share/icons/hicolor/48x48/apps/konversation.png
usr/share/icons/hicolor/64x64/apps/konversation.png
usr/share/icons/hicolor/scalable/actions/kimproxyaway.svgz
usr/share/icons/hicolor/scalable/actions/kimproxyoffline.svgz
usr/share/icons/hicolor/scalable/actions/kimproxyonline.svgz
usr/share/icons/hicolor/scalable/actions/konv_message.svgz
usr/share/icons/hicolor/scalable/apps/konversation.svgz
usr/share/kde4/apps/konversation/*
usr/share/kde4/services/konvirc.protocol
usr/share/kde4/services/konvirc6.protocol
