# Install script for directory: /home/modax/src/konversation/konversation/po

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/modax/src/konversation/konversation/po/bg/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/nb/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ms/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/pl/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ta/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/lt/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/cy/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/sk/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/pt_BR/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/hu/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/zh_CN/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/en_GB/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ru/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/es/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/de/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/sv/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ro/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ko/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/mt/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/pa/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/he/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/sr/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ca/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/zh_TW/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/it/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/uk/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ka/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/sl/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/br/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/nl/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/pt/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/gl/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/fi/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/nds/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/fr/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ja/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ga/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/tr/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/el/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/da/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/hi/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/cs/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/ar/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/is/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/et/cmake_install.cmake")
  INCLUDE("/home/modax/src/konversation/konversation/po/rw/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

