# CMake generated Testfile for 
# Source directory: /home/modax/src/konversation/konversation/po
# Build directory: /home/modax/src/konversation/konversation/po
# 
# This file replicates the SUBDIRS() and ADD_TEST() commands from the source
# tree CMakeLists.txt file, skipping any SUBDIRS() or ADD_TEST() commands
# that are excluded by CMake control structures, i.e. IF() commands.
SUBDIRS(bg)
SUBDIRS(nb)
SUBDIRS(ms)
SUBDIRS(pl)
SUBDIRS(ta)
SUBDIRS(lt)
SUBDIRS(cy)
SUBDIRS(sk)
SUBDIRS(pt_BR)
SUBDIRS(hu)
SUBDIRS(zh_CN)
SUBDIRS(en_GB)
SUBDIRS(ru)
SUBDIRS(es)
SUBDIRS(de)
SUBDIRS(sv)
SUBDIRS(ro)
SUBDIRS(ko)
SUBDIRS(mt)
SUBDIRS(pa)
SUBDIRS(he)
SUBDIRS(sr)
SUBDIRS(ca)
SUBDIRS(zh_TW)
SUBDIRS(it)
SUBDIRS(uk)
SUBDIRS(ka)
SUBDIRS(sl)
SUBDIRS(br)
SUBDIRS(nl)
SUBDIRS(pt)
SUBDIRS(gl)
SUBDIRS(fi)
SUBDIRS(nds)
SUBDIRS(fr)
SUBDIRS(ja)
SUBDIRS(ga)
SUBDIRS(tr)
SUBDIRS(el)
SUBDIRS(da)
SUBDIRS(hi)
SUBDIRS(cs)
SUBDIRS(ar)
SUBDIRS(is)
SUBDIRS(et)
SUBDIRS(rw)
